services:
  - type: web
    name: vbg-verkehrsbetriebe-gravenberg-website
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/ping
    autoDeploy: true
    sync: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://vbg-verkehrsbetriebe-gravenberg-website.onrender.com
      - key: TURSO_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_DISPLAYNAME
        value: Administrator